'\" t
.\"     Title: mdp_worker
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/18/2015
.\"    Manual: Majordomo Manual
.\"    Source: Majordomo 0.1.0
.\"  Language: English
.\"
.TH "MDP_WORKER" "3" "05/18/2015" "Majordomo 0\&.1\&.0" "Majordomo Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mdp_worker \- Majordomo Worker
.SH "SYNOPSIS"
.sp
.nf
//  Create a new mdp_worker
//  Connect to server endpoint and register service\&. Succeed if connection is
//  successful\&.
mdp_worker_t *
    mdp_worker_new (const char *endpoint, const char *service);

//  Destroy the mdp_worker
void
    mdp_worker_destroy (mdp_worker_t **self_p);

//  Return actor, when caller wants to work with multiple actors and/or
//  input sockets asynchronously\&.
zactor_t *
    mdp_worker_actor (mdp_worker_t *self);

//  Return message pipe for asynchronous message I/O\&. In the high\-volume case,
//  we send methods and get replies to the actor, in a synchronous manner, and
//  we send/recv high volume message data to a second pipe, the msgpipe\&. In
//  the low\-volume case we can do everything over the actor pipe, if traffic
//  is never ambiguous\&.
zsock_t *
    mdp_worker_msgpipe (mdp_worker_t *self);

//  Send WORKER PARTIAL\&.
int
    mdp_worker_send_partial (mdp_worker_t *self, zframe_t **address_p, zmsg_t **reply_body_p);

//  Send WORKER FINAL\&.
int
    mdp_worker_send_final (mdp_worker_t *self, zframe_t **address_p, zmsg_t **reply_body_p);

//  Send HEARTBEAT\&.
int
    mdp_worker_send_heartbeat (mdp_worker_t *self);

//  Return last received status
uint8_t
    mdp_worker_status (mdp_worker_t *self);

//  Return last received reason
const char *
    mdp_worker_reason (mdp_worker_t *self);

//  Self test of this class
void
    mdp_worker_test (bool verbose);

//  To enable verbose tracing (animation) of mdp_worker instances, set
//  this to true\&. This lets you trace from and including construction\&.
extern volatile int
    mdp_worker_verbose;
.fi
.SH "DESCRIPTION"
.sp
mdp_worker \- Majordomo Worker
.sp
Please add @discuss section in \&.\&./src/mdp_worker\&.c\&.
.SH "EXAMPLE"
.PP
\fBFrom mdp_worker_test method\fR. 
.sp
.if n \{\
.RS 4
.\}
.nf
//  Simple create/destroy test
mdp_worker_t *self = mdp_worker_new ();
assert (self);
mdp_worker_destroy (&self);
.fi
.if n \{\
.RE
.\}
.sp
.SH "AUTHORS"
.sp
The majordomo manual was written by the authors in the AUTHORS file\&.
.SH "RESOURCES"
.sp
Main web site: \m[blue]\fB\%\fR\m[]
.sp
Report bugs to the email <\m[blue]\fBzeromq\-dev@lists\&.zeromq\&.org\fR\m[]\&\s-2\u[1]\d\s+2>
.SH "COPYRIGHT"
.sp
Copyright (c) the Contributors as noted in the AUTHORS file\&. This file is part of CZMQ, the high\-level C binding for 0MQ: http://czmq\&.zeromq\&.org\&. This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla\&.org/MPL/2\&.0/\&. LICENSE included with the majordomo distribution\&.
.SH "NOTES"
.IP " 1." 4
zeromq-dev@lists.zeromq.org
.RS 4
\%mailto:zeromq-dev@lists.zeromq.org
.RE
